theme:
  name: material

site_name: Voltmeter & Waveform Viewer Project
nav:
  - Home: index.md
  - Hardware:
      - Board: board.md
      - ADC: adc.md
      - SPI: spi.md
      - Voltmeter: voltmeter.md
      - Buttons: buttons.md
      - Display: display.md
  - Software:
      - Program Logic: software.md
      - How to flash the board: howto.md
      - Setting up AVRDUDE: avrdude.md
  - DEMO: demo.md
